[package]
name = "yxo-ports"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.0"
thiserror = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
bytes = { version = "1", features = ["serde"] }