[package]
name = "yxo-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
yxo-ports = { path = "../../crates/ports" }
yxo-adapters = { path = "../../crates/adapters" }
yxo-core = { path = "../../crates/core" }